/* 
 * Copyright 2017 José A. Pacheco Ondoño - joanpaon@gmail.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.japo.java.views;

import java.awt.Color;
import java.util.Properties;
import org.japo.java.controllers.Controller;
import org.japo.java.libraries.UtilesApp;
import org.japo.java.libraries.UtilesValidacion;
import org.japo.java.models.Model;

/**
 *
 * @author José A. Pacheco Ondoño - joanpaon@gmail.com
 */
public class View extends javax.swing.JFrame {
    // Propiedades Vista
    public static final String PRP_PUERTO_BLOQUEO = "puerto_bloqueo";
    public static final String PRP_LOOK_AND_FEEL = "lnf";
    public static final String PRP_RUTA_FAVICON = "ruta_favicon";

    // Fichero Propiedades Vista
    public static final String FICHERO = "view.properties";

    // Referencias
    private Model model;
    private Controller control;
    private Properties prpView;

    // Constructor
    public View() {
        // Inicializacion Anterior
        initBefore();

        // Creación Vista
        initComponents();

        // Inicializacion Posterior
        initAfter();
    }

    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpCur = new javax.swing.ButtonGroup();
        bgpTur = new javax.swing.ButtonGroup();
        pnlIdentificacion = new javax.swing.JPanel();
        lblExp = new javax.swing.JLabel();
        txfExp = new javax.swing.JTextField();
        lblNom = new javax.swing.JLabel();
        txfNom = new javax.swing.JTextField();
        lblApe = new javax.swing.JLabel();
        txfApe = new javax.swing.JTextField();
        lblDNI = new javax.swing.JLabel();
        txfDNI = new javax.swing.JTextField();
        pnlMatricula = new javax.swing.JPanel();
        lblCic = new javax.swing.JLabel();
        cbbCic = new javax.swing.JComboBox();
        LblCur = new javax.swing.JLabel();
        rbtCur1 = new javax.swing.JRadioButton();
        rbtCur2 = new javax.swing.JRadioButton();
        rbtCur3 = new javax.swing.JRadioButton();
        lblTur = new javax.swing.JLabel();
        rbtTurM = new javax.swing.JRadioButton();
        rbtTurV = new javax.swing.JRadioButton();
        rbtTurN = new javax.swing.JRadioButton();
        rbtTurD = new javax.swing.JRadioButton();
        lblRep = new javax.swing.JLabel();
        cbxRep = new javax.swing.JCheckBox();
        pnlPersistencia = new javax.swing.JPanel();
        btnImportar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matricula Centro Formativo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlIdentificacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Identificación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        lblExp.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblExp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblExp.setText("Expediente");

        txfExp.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txfExp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfExpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfExpFocusLost(evt);
            }
        });

        lblNom.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblNom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNom.setText("Nombre");

        txfNom.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txfNom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfNomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfNomFocusLost(evt);
            }
        });

        lblApe.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblApe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblApe.setText("Apellidos");

        txfApe.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txfApe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfApeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfApeFocusLost(evt);
            }
        });

        lblDNI.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblDNI.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDNI.setText("Nif");

        txfDNI.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txfDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfDNIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfDNIFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlIdentificacionLayout = new javax.swing.GroupLayout(pnlIdentificacion);
        pnlIdentificacion.setLayout(pnlIdentificacionLayout);
        pnlIdentificacionLayout.setHorizontalGroup(
            pnlIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdentificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIdentificacionLayout.createSequentialGroup()
                        .addGroup(pnlIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblExp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfNom)
                            .addComponent(txfExp)))
                    .addGroup(pnlIdentificacionLayout.createSequentialGroup()
                        .addGroup(pnlIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDNI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(pnlIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfApe)
                            .addComponent(txfDNI))))
                .addContainerGap())
        );

        pnlIdentificacionLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblApe, lblDNI, lblExp, lblNom});

        pnlIdentificacionLayout.setVerticalGroup(
            pnlIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdentificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApe, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlIdentificacionLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblApe, lblDNI, lblExp, lblNom, txfApe, txfDNI, txfExp, txfNom});

        pnlMatricula.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Matrícula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        lblCic.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCic.setText("Ciclo");

        cbbCic.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cbbCic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DAI", "ASI", "ESI", "SMR", "ASIR", "DAW", "DAM", "" }));
        cbbCic.setSelectedItem(Model.DEF_CIC);

        LblCur.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        LblCur.setText("Curso");

        bgpCur.add(rbtCur1);
        rbtCur1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        rbtCur1.setSelected(true);
        rbtCur1.setText("1");

        bgpCur.add(rbtCur2);
        rbtCur2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        rbtCur2.setText("2");

        bgpCur.add(rbtCur3);
        rbtCur3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        rbtCur3.setText("3");

        lblTur.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTur.setText("Turno");

        bgpTur.add(rbtTurM);
        rbtTurM.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        rbtTurM.setSelected(true);
        rbtTurM.setText("M");

        bgpTur.add(rbtTurV);
        rbtTurV.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        rbtTurV.setText("V");

        bgpTur.add(rbtTurN);
        rbtTurN.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        rbtTurN.setText("N");

        bgpTur.add(rbtTurD);
        rbtTurD.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        rbtTurD.setText("D");

        lblRep.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblRep.setText("Repetidor");

        cbxRep.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout pnlMatriculaLayout = new javax.swing.GroupLayout(pnlMatricula);
        pnlMatricula.setLayout(pnlMatriculaLayout);
        pnlMatriculaLayout.setHorizontalGroup(
            pnlMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMatriculaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMatriculaLayout.createSequentialGroup()
                        .addGroup(pnlMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblCur, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbCic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlMatriculaLayout.createSequentialGroup()
                        .addGroup(pnlMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMatriculaLayout.createSequentialGroup()
                                .addComponent(lblTur, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtCur1)
                                    .addComponent(rbtTurM))
                                .addGap(12, 12, 12)
                                .addGroup(pnlMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMatriculaLayout.createSequentialGroup()
                                        .addComponent(rbtTurV)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtTurN)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtTurD))
                                    .addGroup(pnlMatriculaLayout.createSequentialGroup()
                                        .addComponent(rbtCur2)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtCur3))))
                            .addGroup(pnlMatriculaLayout.createSequentialGroup()
                                .addComponent(lblRep, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxRep)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pnlMatriculaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {LblCur, lblCic, lblRep, lblTur});

        pnlMatriculaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbtCur1, rbtCur2, rbtCur3, rbtTurD, rbtTurM, rbtTurN, rbtTurV});

        pnlMatriculaLayout.setVerticalGroup(
            pnlMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMatriculaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCic, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbCic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCur)
                    .addComponent(rbtCur1)
                    .addComponent(rbtCur2)
                    .addComponent(rbtCur3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTur, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtTurM)
                    .addComponent(rbtTurV)
                    .addComponent(rbtTurN)
                    .addComponent(rbtTurD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRep)
                    .addComponent(cbxRep))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMatriculaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {LblCur, cbbCic, lblCic, lblRep, lblTur, rbtCur1, rbtCur2, rbtCur3, rbtTurD, rbtTurM, rbtTurN, rbtTurV});

        pnlPersistencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Persistencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        btnImportar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnImportar.setText("Importar");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        btnExportar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPersistenciaLayout = new javax.swing.GroupLayout(pnlPersistencia);
        pnlPersistencia.setLayout(pnlPersistenciaLayout);
        pnlPersistenciaLayout.setHorizontalGroup(
            pnlPersistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersistenciaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pnlPersistenciaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExportar, btnImportar});

        pnlPersistenciaLayout.setVerticalGroup(
            pnlPersistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersistenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPersistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImportar)
                    .addComponent(btnExportar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlPersistencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPersistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        control.procesarImportacion(evt);
    }//GEN-LAST:event_btnImportarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        control.procesarExportacion(evt);
    }//GEN-LAST:event_btnExportarActionPerformed

    private void txfExpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfExpFocusGained
        txfExp.setForeground(Color.BLACK);
        txfExp.setBackground(Color.CYAN);
    }//GEN-LAST:event_txfExpFocusGained

    private void txfNomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfNomFocusGained
        txfNom.setForeground(Color.BLACK);
        txfNom.setBackground(Color.CYAN);
    }//GEN-LAST:event_txfNomFocusGained

    private void txfApeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfApeFocusGained
        txfApe.setForeground(Color.BLACK);
        txfApe.setBackground(Color.CYAN);
    }//GEN-LAST:event_txfApeFocusGained

    private void txfDNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfDNIFocusGained
        txfDNI.setForeground(Color.BLACK);
        txfDNI.setBackground(Color.CYAN);
    }//GEN-LAST:event_txfDNIFocusGained

    private void txfExpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfExpFocusLost
        UtilesValidacion.validarCampoTexto(txfExp, Model.ER_EXP, "*");
        txfExp.setBackground(Color.WHITE);
    }//GEN-LAST:event_txfExpFocusLost

    private void txfNomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfNomFocusLost
        UtilesValidacion.validarCampoTexto(txfNom, Model.ER_NOM, "*");
        txfNom.setBackground(Color.WHITE);
    }//GEN-LAST:event_txfNomFocusLost

    private void txfApeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfApeFocusLost
        UtilesValidacion.validarCampoTexto(txfApe, Model.ER_APE, "*");
        txfApe.setBackground(Color.WHITE);
    }//GEN-LAST:event_txfApeFocusLost

    private void txfDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfDNIFocusLost
        UtilesValidacion.validarCampoDNI(txfDNI, "99999999Z");
        txfDNI.setBackground(Color.WHITE);
    }//GEN-LAST:event_txfDNIFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        control.procesarCierreVista(evt);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblCur;
    public javax.swing.ButtonGroup bgpCur;
    public javax.swing.ButtonGroup bgpTur;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnImportar;
    public javax.swing.JComboBox cbbCic;
    public javax.swing.JCheckBox cbxRep;
    private javax.swing.JLabel lblApe;
    private javax.swing.JLabel lblCic;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblExp;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblRep;
    private javax.swing.JLabel lblTur;
    private javax.swing.JPanel pnlIdentificacion;
    private javax.swing.JPanel pnlMatricula;
    private javax.swing.JPanel pnlPersistencia;
    public javax.swing.JRadioButton rbtCur1;
    public javax.swing.JRadioButton rbtCur2;
    public javax.swing.JRadioButton rbtCur3;
    public javax.swing.JRadioButton rbtTurD;
    public javax.swing.JRadioButton rbtTurM;
    public javax.swing.JRadioButton rbtTurN;
    public javax.swing.JRadioButton rbtTurV;
    public javax.swing.JTextField txfApe;
    public javax.swing.JTextField txfDNI;
    public javax.swing.JTextField txfExp;
    public javax.swing.JTextField txfNom;
    // End of variables declaration//GEN-END:variables

    // Inicializacion Anterior
    private void initBefore() {
        // Crear Modelo
        model = new Model();

        // Crear Controlador
        control = new Controller(model, this);

        // Cargar Propiedades Vista
        prpView = UtilesApp.cargarPropiedades(FICHERO);

        // Restaurar Estado
        control.restaurarEstadoVista(this, prpView);

        // Otras inicializaciones
    }

    // Inicializacion Posterior
    private void initAfter() {
        // Modelo > Vista
        control.sincronizarModeloVista(model, this);

        // Enfocar Control Inicial
        txfExp.requestFocus();

        // Otras inicializaciones
    }
}
